name: Deploy Terraform Configuration

# on: 
#   push:
#   workflow_dispatch: # 手動トリガーを追加

jobs:
  deploy-terraform:
    name: Apply Terraform Configuration to AWS
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0  # 必要なTerraformのバージョンを指定

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: cd terraform && terraform init

    - name: Terraform Plan
      run: cd terraform && terraform plan

    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve